name: Create and upload gd-blog-ui docker image
on: [push]
jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
          docker build -t zou8944/gd-blog-ui:latest .
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push zou8944/gd-blog-ui:latest
          docker logout