name: Create and upload gd-blog-ui docker image
on: [push]
jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
          docker build -t registry.cn-shenzhen.aliyuncs.com/zou8944/gd-blog-ui:latest --platform linux/amd64 .
      - name: Publish to docker hub
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
          docker push registry.cn-shenzhen.aliyuncs.com/zou8944/gd-blog-ui:latest
          docker logout
      - name: Trigger re config server
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            https://api.github.com/repos/zou8944/gd-server-config/dispatches \
            -d '{"event_type":"re-deploy","client_payload":{"blog-server-success": true}}'